"""migrate the all  table

Revision ID: 089c5b41878a
Revises: 182887c5b74f
Create Date: 2024-01-22 19:18:32.344275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import json



geo_json = json.dumps({"lat": 40.7128, "lon": -74.0060})


# revision identifiers, used by Alembic.
revision: str = '089c5b41878a'
down_revision: Union[str, None] = '182887c5b74f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.execute("INSERT INTO city (id, city, district, state, country) VALUES (1, 'Mahmoodabad', 'Sitapur', 'Uttar Pradesh', 'India')")
    # Insert data into 'location' table
    
    op.execute(
    "INSERT INTO location (id, geo_id, address1, address2, landmark, city_id, zip_code) "
    f"VALUES (1, '{geo_json}', 'Sample Address 1', 'Sample Address 2', 'Sample Landmark', 1, 123456)"
)
    # Insert data into 'multilingual_text' table
    op.execute(
    "INSERT INTO multilingual_text (id, `keys`, lang_code, display_text) VALUES (1, 123, 3, 'Hello, World!')"
)

    # Insert data into 'b2b_tenant' table
    op.execute(
        "INSERT INTO b2b_tenant (id, name, ml_name, location_id, media) VALUES (1, 'Sample Tenant', 'Sample ML Tenant', 1, 'Sample Media')"
    )

    # Insert data into 'qomplnt_or' table
    op.execute(
        "INSERT INTO qomplnt_or (id, uuid, location_id, b2b_tenant_id, ml_quote, ml_sub_text, sub_media) "
        "VALUES (1, '12345678', 1, 1, 'Sample Quote', 'Sample Subtext', 'Sample Submedia')"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
